services:
  iblog-frontend-layout:
    container_name: iblog_frontend
    build:
      context: .
      dockerfile: ./devops/Dockerfile
    ports:
      - "3000:3000"
    image: iblog_frontend:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - iblog_network

networks:
  iblog_network:
    external: true
