services:
  iblog-frontend:
    container_name: iblog-frontend
    build:
      context: .
      dockerfile: ./devops/Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - TZ=Africa/Lagos
    networks:
      - iblog_network

networks:
  iblog_network:
    external: true
