name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Rsync project to VPS
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }}" ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/dockerlized-apps/react-next-app/iblog-frontend/

      - name: Create .env file on VPS
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cat > ~/dockerlized-apps/react-next-app/iblog-frontend/.env <<EOL
            NEXT_PUBLIC_PRODUCTION=${{ secrets.NEXT_PUBLIC_PRODUCTION }}
            NEXT_PUBLIC_PRODUCTION_SERVER_URL=${{ secrets.NEXT_PUBLIC_PRODUCTION_SERVER_URL }}
            NEXT_PUBLIC_GOOGLE_PRODUCTION_REDIRECT_URI=${{ secrets.NEXT_PUBLIC_GOOGLE_PRODUCTION_REDIRECT_URI }}
            NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
            WEBSOCKET_URL=${{ secrets.WEBSOCKET_URL }}
            EOL
          EOF

      - name: SSH and restart Docker
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ~/dockerlized-apps/react-next-app/iblog-frontend
            docker compose down
            docker compose up -d --build
          EOF
